language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - python --version
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade codecov pytest
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

