language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install: "pip install -r requirements.txt"

script:
  - pytest --cov=./
  
after_success:
  - codecov

before_install:
  - python --version
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade codecov pytest
install:
  - pip install ".[test]"
script: pytest
after_success:
  - codecov # submit coverage